apiVersion: v1
kind: Secret
metadata:
  name: observex-agent-credentials
type: Opaque
stringData:
  ingestURL: {{ .Values.observex.ingestURL | required "observex.ingestURL is required" | quote }}
  agentToken: {{ .Values.observex.agentToken | required "observex.agentToken is required" | quote }}
  clusterName: {{ .Values.observex.clusterName | required "observex.clusterName is required" | quote }}
